DELETE FROM possalesdetails;
DELETE FROM possalespayments;
DELETE FROM possales;
DELETE FROM supplierproducts;
DELETE FROM goodsreceiveddetails;
DELETE FROM goodsreceived;
DELETE FROM purchaseorderdetails;
DELETE FROM purchaseorderapproval;
DELETE FROM purchaseorders;
DELETE FROM supplierinvoicedetails;
DELETE FROM supplierinvoice;
DELETE FROM paymentvoucherdetails;
DELETE FROM paymentvouchers;
DELETE FROM stockmovementsalesdetails;
DELETE FROM stockmovement;
DELETE FROM stockreconciledbalancedetails;
DELETE FROM stockreconciledbalance;
DELETE FROM stocktransferdetails;
DELETE FROM stocktransfer;
DELETE FROM spoilage;
DELETE FROM tempcustomerreceiptdetails;
DELETE FROM tempgoodsreceived;
DELETE FROM tempjournaldetails;
DELETE FROM temppaymentvoucherdetails;
DELETE FROM temppossalespayment;
DELETE FROM temppricematrix;
DELETE FROM tempprivilege;
DELETE FROM temppurchaseorder;
DELETE FROM tempreceiptno;
DELETE FROM tempreturns;
DELETE FROM tempsale;
DELETE FROM tempstockreconcilebalancedetails;
DELETE FROM tempstocktransfer;
DELETE FROM tempsupplierinvoice;
DELETE FROM `tables`;
DELETE FROM supplierproducts;
DELETE FROM tempbanking;
DELETE FROM gltransactions;
DELETE FROM journaldetails;
DELETE FROM journals;
DELETE FROM heldsales;
DELETE FROM heldsalesdetails;
DELETE FROM cratesinventory;
DELETE FROM products;
DELETE FROM categories;
DELETE FROM useroutlets;
DELETE FROM userprivileges;
DELETE FROM roleusers;
DELETE FROM customercontacts;
DELETE FROM `customerreceiptdetails`;
DELETE FROM `customerreceipts`;
DELETE FROM `customersuspenseaccount`;
DELETE FROM customers;
DELETE FROM pointsofsale;
DELETE FROM suppliers;
DELETE FROM `user` WHERE username!='admin';
DELETE FROM `zones`;

-- Reseed the tables identity fields
ALTER TABLE  possalesdetails AUTO_INCREMENT=1;
ALTER TABLE  possalespayments AUTO_INCREMENT=1;
ALTER TABLE  possales AUTO_INCREMENT=1;
ALTER TABLE  supplierproducts AUTO_INCREMENT=1;
ALTER TABLE  goodsreceiveddetails AUTO_INCREMENT=1;
ALTER TABLE  goodsreceived AUTO_INCREMENT=1;
ALTER TABLE  purchaseorderdetails AUTO_INCREMENT=1;
ALTER TABLE  purchaseorderapproval AUTO_INCREMENT=1;
ALTER TABLE  purchaseorders AUTO_INCREMENT=1;
ALTER TABLE  supplierinvoicedetails AUTO_INCREMENT=1;
ALTER TABLE  supplierinvoice AUTO_INCREMENT=1;
ALTER TABLE  paymentvoucherdetails AUTO_INCREMENT=1;
ALTER TABLE  paymentvouchers AUTO_INCREMENT=1;
ALTER TABLE  stockmovementsalesdetails AUTO_INCREMENT=1;
ALTER TABLE  stockmovement AUTO_INCREMENT=1;
ALTER TABLE  stockreconciledbalancedetails AUTO_INCREMENT=1;
ALTER TABLE  stockreconciledbalance AUTO_INCREMENT=1;
ALTER TABLE  stocktransferdetails AUTO_INCREMENT=1;
ALTER TABLE  stocktransfer AUTO_INCREMENT=1;
ALTER TABLE  spoilage AUTO_INCREMENT=1;
ALTER TABLE  `tables` AUTO_INCREMENT=1;
ALTER TABLE  supplierproducts AUTO_INCREMENT=1;
ALTER TABLE  tempbanking AUTO_INCREMENT=1;
ALTER TABLE  gltransactions AUTO_INCREMENT=1;
ALTER TABLE  journaldetails AUTO_INCREMENT=1;
ALTER TABLE  journals AUTO_INCREMENT=1;
ALTER TABLE  heldsales AUTO_INCREMENT=1;
ALTER TABLE  heldsalesdetails AUTO_INCREMENT=1;
ALTER TABLE  cratesinventory AUTO_INCREMENT=1;
ALTER TABLE  products AUTO_INCREMENT=1;
ALTER TABLE  categories AUTO_INCREMENT=1;
ALTER TABLE  useroutlets AUTO_INCREMENT=1;
ALTER TABLE  userprivileges AUTO_INCREMENT=1;
ALTER TABLE  roleusers AUTO_INCREMENT=1;
ALTER TABLE customercontacts AUTO_INCREMENT=1;
ALTER TABLE customerreceipts AUTO_INCREMENT=1;
ALTER TABLE customerreceiptdetails AUTO_INCREMENT=1;
ALTER TABLE customersuspenseaccount AUTO_INCREMENT=1;
ALTER TABLE  customers AUTO_INCREMENT=1;
ALTER TABLE  suppliers AUTO_INCREMENT=1;
ALTER TABLE  pointsofsale AUTO_INCREMENT=1;
ALTER TABLE `zones` AUTO_INCREMENT=1