-- Geography Database Update Script
-- Combined Countries and Cities Data

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `cities`;
DROP TABLE IF EXISTS `countries`;
SET FOREIGN_KEY_CHECKS = 1;

-- Create countries table
CREATE TABLE `countries` (
  `countryid` int(11) NOT NULL AUTO_INCREMENT,
  `countryname` varchar(100) NOT NULL,
  `countrycode` varchar(10) DEFAULT NULL,
  `currency` varchar(50) DEFAULT NULL,
  `currencysymbol` varchar(10) DEFAULT NULL,
  `dialingcode` varchar(10) DEFAULT NULL,
  `isdefault` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`countryid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Populate countries
INSERT INTO `countries` (countryname, countrycode, currency, currencysymbol, dialingcode, isdefault) VALUES
('Afghanistan', 'AF', 'Afghani', '؋', '+93', 0),
('Albania', 'AL', 'Lek', 'Lek', '+355', 0),
('Algeria', 'DZ', 'Algerian Dinar', '', '+213', 0),
('American Samoa', 'AS', 'US Dollar', '$', '+1', 0),
('Andorra', 'AD', 'Euro', '€', '+376', 0),
('Angola', 'AO', 'Kwanza', '', '+244', 0),
('Anguilla', 'AI', 'East Caribbean Dollar', '$', '+1', 0),
('Antarctica', 'AQ', '', '', '+672', 0),
('Antigua and Barbuda', 'AG', 'East Caribbean Dollar', '$', '+1', 0),
('Argentina', 'AR', 'Argentine Peso', '$', '+54', 0),
('Armenia', 'AM', 'Armenian Dram', '', '+374', 0),
('Aruba', 'AW', 'Aruban Florin', 'ƒ', '+297', 0),
('Australia', 'AU', 'Australian Dollar', '$', '+61', 0),
('Austria', 'AT', 'Euro', '€', '+43', 0),
('Azerbaijan', 'AZ', 'Azerbaijanian Manat', 'ман', '+994', 0),
('Bahamas', 'BS', 'Bahamian Dollar', '$', '+1', 0),
('Bahrain', 'BH', 'Bahraini Dinar', '', '+973', 0),
('Bangladesh', 'BD', 'Taka', '', '+880', 0),
('Barbados', 'BB', 'Barbados Dollar', '$', '+1', 0),
('Belarus', 'BY', 'Belarussian Ruble', 'p.', '+375', 0),
('Belgium', 'BE', 'Euro', '€', '+32', 0),
('Belize', 'BZ', 'Belize Dollar', 'BZ$', '+501', 0),
('Benin', 'BJ', 'CFA Franc BCEAO', '', '+229', 0),
('Bermuda', 'BM', 'Bermudian Dollar', '$', '+1', 0),
('Bhutan', 'BT', 'Indian Rupee', '₹', '+975', 0),
('Bolivia, Plurinational State of', 'BO', 'Boliviano', '$b', '+591', 0),
('Bonaire, Sint Eustatius and Saba', 'BQ', 'US Dollar', '$', '+599', 0),
('Bosnia and Herzegovina', 'BA', 'Convertible Mark', 'KM', '+387', 0),
('Botswana', 'BW', 'Pula', 'P', '+267', 0),
('Bouvet Island', 'BV', 'Norwegian Krone', 'kr', '+47', 0),
('Brazil', 'BR', 'Brazilian Real', 'R$', '+55', 0),
('British Indian Ocean Territory', 'IO', 'US Dollar', '$', '+246', 0),
('Brunei Darussalam', 'BN', 'Brunei Dollar', '$', '+673', 0),
('Bulgaria', 'BG', 'Bulgarian Lev', 'лв', '+359', 0),
('Burkina Faso', 'BF', 'CFA Franc BCEAO', '', '+226', 0),
('Burundi', 'BI', 'Burundi Franc', 'FBu', '+257', 0),
('Cambodia', 'KH', 'Riel', '៛', '+855', 0),
('Cameroon', 'CM', 'CFA Franc BEAC', '', '+237', 0),
('Canada', 'CA', 'Canadian Dollar', '$', '+1', 0),
('Cape Verde', 'CV', 'Cabo Verde Escudo', '', '+238', 0),
('Cayman Islands', 'KY', 'Cayman Islands Dollar', '$', '+1', 0),
('Central African Republic', 'CF', 'CFA Franc BEAC', '', '+236', 0),
('Chad', 'TD', 'CFA Franc BEAC', '', '+235', 0),
('Chile', 'CL', 'Chilean Peso', '$', '+56', 0),
('China', 'CN', 'Yuan Renminbi', '¥', '+86', 0),
('Christmas Island', 'CX', 'Australian Dollar', '$', '+61', 0),
('Cocos (Keeling) Islands', 'CC', 'Australian Dollar', '$', '+61', 0),
('Colombia', 'CO', 'Colombian Peso', '$', '+57', 0),
('Comoros', 'KM', 'Comoro Franc', '', '+269', 0),
('Congo', 'CG', 'CFA Franc BEAC', '', '+242', 0),
('Congo, the Democratic Republic of the', 'CD', '', '', '+243', 0),
('Cook Islands', 'CK', 'New Zealand Dollar', '$', '+682', 0),
('Costa Rica', 'CR', 'Costa Rican Colon', '₡', '+506', 0),
('Croatia', 'HR', 'Croatian Kuna', 'kn', '+385', 0),
('Cuba', 'CU', 'Cuban Peso', '₱', '+53', 0),
('Curaçao', 'CW', 'Netherlands Antillean Guilder', 'ƒ', '+599', 0),
('Cyprus', 'CY', 'Euro', '€', '+357', 0),
('Czech Republic', 'CZ', 'Czech Koruna', 'Kč', '+420', 0),
('Denmark', 'DK', 'Danish Krone', 'kr', '+45', 0),
('Djibouti', 'DJ', 'Djibouti Franc', '', '+253', 0),
('Dominica', 'DM', 'East Caribbean Dollar', '$', '+1', 0),
('Dominican Republic', 'DO', 'Dominican Peso', '', '+1', 0),
('Ecuador', 'EC', 'US Dollar', '$', '+593', 0),
('Egypt', 'EG', 'Egyptian Pound', '£', '+20', 0),
('El Salvador', 'SV', 'US Dollar', '$', '+503', 0),
('Equatorial Guinea', 'GQ', 'CFA Franc BEAC', '', '+240', 0),
('Eritrea', 'ER', 'Nakfa', '', '+291', 0),
('Estonia', 'EE', 'Euro', '€', '+372', 0),
('Ethiopia', 'ET', 'Ethiopian Birr', 'Br', '+251', 0),
('Falkland Islands (Malvinas)', 'FK', 'Falkland Islands Pound', '£', '+500', 0),
('Faroe Islands', 'FO', 'Danish Krone', 'kr', '+298', 0),
('Fiji', 'FJ', 'Fiji Dollar', '$', '+679', 0),
('Finland', 'FI', 'Euro', '€', '+358', 0),
('France', 'FR', 'Euro', '€', '+33', 0),
('French Guiana', 'GF', 'Euro', '€', '+594', 0),
('French Polynesia', 'PF', 'CFP Franc', '', '+689', 0),
('French Southern Territories', 'TF', 'Euro', '€', '+262', 0),
('Gabon', 'GA', 'CFA Franc BEAC', '', '+241', 0),
('Gambia', 'GM', 'Dalasi', '', '+220', 0),
('Georgia', 'GE', 'Lari', '', '+995', 0),
('Germany', 'DE', 'Euro', '€', '+49', 0),
('Ghana', 'GH', 'Ghana Cedi', '', '+233', 0),
('Gibraltar', 'GI', 'Gibraltar Pound', '£', '+350', 0),
('Greece', 'GR', 'Euro', '€', '+30', 0),
('Greenland', 'GL', 'Danish Krone', 'kr', '+299', 0),
('Grenada', 'GD', 'East Caribbean Dollar', '$', '+1', 0),
('Guadeloupe', 'GP', 'Euro', '€', '+590', 0),
('Guam', 'GU', 'US Dollar', '$', '+1', 0),
('Guatemala', 'GT', 'Quetzal', 'Q', '+502', 0),
('Guernsey', 'GG', 'Pound Sterling', '£', '+44', 0),
('Guinea', 'GN', 'Guinea Franc', '', '+224', 0),
('Guinea-Bissau', 'GW', 'CFA Franc BCEAO', '', '+245', 0),
('Guyana', 'GY', 'Guyana Dollar', '$', '+592', 0),
('Haiti', 'HT', 'US Dollar', '$', '+509', 0),
('Heard Island and McDonald Islands', 'HM', 'Australian Dollar', '$', '+672', 0),
('Holy See (Vatican City State)', 'VA', 'Euro', '€', '+39', 0),
('Honduras', 'HN', 'Lempira', 'L', '+504', 0),
('Hong Kong', 'HK', 'Hong Kong Dollar', '$', '+852', 0),
('Hungary', 'HU', 'Forint', 'Ft', '+36', 0),
('Iceland', 'IS', 'Iceland Krona', 'kr', '+354', 0),
('India', 'IN', 'Indian Rupee', '₹', '+91', 0),
('Indonesia', 'ID', 'Rupiah', 'Rp', '+62', 0),
('Iran, Islamic Republic of', 'IR', 'Iranian Rial', '﷼', '+98', 0),
('Iraq', 'IQ', 'Iraqi Dinar', '', '+964', 0),
('Ireland', 'IE', 'Euro', '€', '+353', 0),
('Isle of Man', 'IM', 'Pound Sterling', '£', '+44', 0),
('Israel', 'IL', 'New Israeli Sheqel', '₪', '+972', 0),
('Italy', 'IT', 'Euro', '€', '+39', 0),
('Jamaica', 'JM', 'Jamaican Dollar', 'J$', '+1', 0),
('Japan', 'JP', 'Yen', '¥', '+81', 0),
('Jersey', 'JE', 'Pound Sterling', '£', '+44', 0),
('Jordan', 'JO', 'Jordanian Dinar', '', '+962', 0),
('Kazakhstan', 'KZ', 'Tenge', 'лв', '+7', 0),
('Kenya', 'KE', 'Kenyan Shilling', 'KSh', '+254', 1),
('Kiribati', 'KI', 'Australian Dollar', '$', '+686', 0),
('Korea, Republic of', 'KR', 'Won', '₩', '+82', 0),
('Kuwait', 'KW', 'Kuwaiti Dinar', '', '+965', 0),
('Kyrgyzstan', 'KG', 'Som', 'лв', '+996', 0),
('Latvia', 'LV', 'Euro', '€', '+371', 0),
('Lebanon', 'LB', 'Lebanese Pound', '£', '+961', 0),
('Lesotho', 'LS', 'Rand', 'R', '+266', 0),
('Liberia', 'LR', 'Liberian Dollar', '$', '+231', 0),
('Libya', 'LY', 'Libyan Dinar', '', '+218', 0),
('Liechtenstein', 'LI', 'Swiss Franc', 'CHF', '+423', 0),
('Lithuania', 'LT', 'Euro', '€', '+370', 0),
('Luxembourg', 'LU', 'Euro', '€', '+352', 0),
('Macao', 'MO', 'Pataca', '', '+853', 0),
('Macedonia, the Former Yugoslav Republic of', 'MK', 'Denar', 'ден', '+389', 0),
('Madagascar', 'MG', 'Malagasy Ariary', '', '+261', 0),
('Malawi', 'MW', 'Kwacha', '', '+265', 0),
('Malaysia', 'MY', 'Malaysian Ringgit', 'RM', '+60', 0),
('Maldives', 'MV', 'Rufiyaa', '', '+960', 0),
('Mali', 'ML', 'CFA Franc BCEAO', '', '+223', 0),
('Malta', 'MT', 'Euro', '€', '+356', 0),
('Marshall Islands', 'MH', 'US Dollar', '$', '+692', 0),
('Martinique', 'MQ', 'Euro', '€', '+596', 0),
('Mauritania', 'MR', 'Ouguiya', '', '+222', 0),
('Mauritius', 'MU', 'Mauritius Rupee', '₨', '+230', 0),
('Mayotte', 'YT', 'Euro', '€', '+262', 0),
('Mexico', 'MX', 'Mexican Peso', '$', '+52', 0),
('Micronesia, Federated States of', 'FM', 'US Dollar', '$', '+691', 0),
('Moldova, Republic of', 'MD', 'Moldovan Leu', '', '+373', 0),
('Monaco', 'MC', 'Euro', '€', '+377', 0),
('Mongolia', 'MN', 'Tugrik', '₮', '+976', 0),
('Montenegro', 'ME', 'Euro', '€', '+382', 0),
('Montserrat', 'MS', 'East Caribbean Dollar', '$', '+1', 0),
('Morocco', 'MA', 'Moroccan Dirham', '', '+212', 0),
('Mozambique', 'MZ', 'Mozambique Metical', 'MT', '+258', 0),
('Myanmar', 'MM', 'Kyat', '', '+95', 0),
('Namibia', 'NA', 'Rand', 'R', '+264', 0),
('Nauru', 'NR', 'Australian Dollar', '$', '+674', 0),
('Nepal', 'NP', 'Nepalese Rupee', '₨', '+977', 0),
('Netherlands', 'NL', 'Euro', '€', '+31', 0),
('New Caledonia', 'NC', 'CFP Franc', '', '+687', 0),
('New Zealand', 'NZ', 'New Zealand Dollar', '$', '+64', 0),
('Nicaragua', 'NI', 'Cordoba Oro', 'C$', '+505', 0),
('Niger', 'NE', 'CFA Franc BCEAO', '', '+227', 0),
('Nigeria', 'NG', 'Naira', '₦', '+234', 0),
('Niue', 'NU', 'New Zealand Dollar', '$', '+683', 0),
('Norfolk Island', 'NF', 'Australian Dollar', '$', '+672', 0),
('Northern Mariana Islands', 'MP', 'US Dollar', '$', '+1', 0),
('Norway', 'NO', 'Norwegian Krone', 'kr', '+47', 0),
('Oman', 'OM', 'Rial Omani', '﷼', '+968', 0),
('Pakistan', 'PK', 'Pakistan Rupee', '₨', '+92', 0),
('Palau', 'PW', 'US Dollar', '$', '+680', 0),
('Palestine, State of', 'PS', '', '', '+970', 0),
('Panama', 'PA', 'US Dollar', '$', '+507', 0),
('Papua New Guinea', 'PG', 'Kina', '', '+675', 0),
('Paraguay', 'PY', 'Guarani', 'Gs', '+595', 0),
('Peru', 'PE', 'Nuevo Sol', 'S/.', '+51', 0),
('Philippines', 'PH', 'Philippine Peso', 'Php', '+63', 0),
('Pitcairn', 'PN', 'New Zealand Dollar', '$', '+870', 0),
('Poland', 'PL', 'Zloty', 'zł', '+48', 0),
('Portugal', 'PT', 'Euro', '€', '+351', 0),
('Puerto Rico', 'PR', 'US Dollar', '$', '+1', 0),
('Qatar', 'QA', 'Qatari Rial', '﷼', '+974', 0),
('Romania', 'RO', 'New Romanian Leu', 'lei', '+40', 0),
('Russian Federation', 'RU', 'Russian Ruble', 'руб', '+7', 0),
('Rwanda', 'RW', 'Rwanda Franc', 'RF', '+250', 0),
('Réunion', 'RE', 'Euro', '€', '+262', 0),
('Saint Barthélemy', 'BL', 'Euro', '€', '+590', 0),
('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'Saint Helena Pound', '£', '+290', 0),
('Saint Kitts and Nevis', 'KN', 'East Caribbean Dollar', '$', '+1', 0),
('Saint Lucia', 'LC', 'East Caribbean Dollar', '$', '+1', 0),
('Saint Martin (French part)', 'MF', 'Euro', '€', '+590', 0),
('Saint Pierre and Miquelon', 'PM', 'Euro', '€', '+508', 0),
('Saint Vincent and the Grenadines', 'VC', 'East Caribbean Dollar', '$', '+1', 0),
('Samoa', 'WS', 'Tala', '', '+685', 0),
('San Marino', 'SM', 'Euro', '€', '+378', 0),
('Sao Tome and Principe', 'ST', 'Dobra', '', '+239', 0),
('Saudi Arabia', 'SA', 'Saudi Riyal', '﷼', '+966', 0),
('Senegal', 'SN', 'CFA Franc BCEAO', '', '+221', 0),
('Serbia', 'RS', 'Serbian Dinar', 'Дин.', '+381', 0),
('Seychelles', 'SC', 'Seychelles Rupee', '₨', '+248', 0),
('Sierra Leone', 'SL', 'Leone', '', '+232', 0),
('Singapore', 'SG', 'Singapore Dollar', '$', '+65', 0),
('Sint Maarten (Dutch part)', 'SX', 'Netherlands Antillean Guilder', 'ƒ', '+1', 0),
('Slovakia', 'SK', 'Euro', '€', '+421', 0),
('Slovenia', 'SI', 'Euro', '€', '+386', 0),
('Solomon Islands', 'SB', 'Solomon Islands Dollar', '$', '+677', 0),
('Somalia', 'SO', 'Somali Shilling', 'Sh.So.', '+252', 0),
('South Africa', 'ZA', 'Rand', 'R', '+27', 0),
('South Georgia and the South Sandwich Islands', 'GS', '', '', '+500', 0),
('South Sudan', 'SS', 'South Sudanese Pound', 'SSP', '+211', 0),
('Spain', 'ES', 'Euro', '€', '+34', 0),
('Sri Lanka', 'LK', 'Sri Lanka Rupee', '₨', '+94', 0),
('Sudan', 'SD', 'Sudanese Pound', '', '+249', 0),
('Suriname', 'SR', 'Surinam Dollar', '$', '+597', 0),
('Svalbard and Jan Mayen', 'SJ', 'Norwegian Krone', 'kr', '+47', 0),
('Swaziland', 'SZ', 'Lilangeni', '', '+268', 0),
('Sweden', 'SE', 'Swedish Krona', 'kr', '+46', 0),
('Switzerland', 'CH', 'Swiss Franc', 'CHF', '+41', 0),
('Syrian Arab Republic', 'SY', 'Syrian Pound', '£', '+963', 0),
('Taiwan, Province of China', 'TW', 'New Taiwan Dollar', 'NT$', '+886', 0),
('Tajikistan', 'TJ', 'Somoni', '', '+992', 0),
('Tanzania, United Republic of', 'TZ', 'Tanzanian Shilling', 'TSh', '+255', 0),
('Thailand', 'TH', 'Baht', '฿', '+66', 0),
('Timor-Leste', 'TL', 'US Dollar', '$', '+670', 0),
('Togo', 'TG', 'CFA Franc BCEAO', '', '+228', 0),
('Tokelau', 'TK', 'New Zealand Dollar', '$', '+690', 0),
('Tonga', 'TO', 'Pa’anga', '', '+676', 0),
('Trinidad and Tobago', 'TT', 'Trinidad and Tobago Dollar', 'TT$', '+1', 0),
('Tunisia', 'TN', 'Tunisian Dinar', '', '+216', 0),
('Turkey', 'TR', 'Turkish Lira', 'TL', '+90', 0),
('Turkmenistan', 'TM', 'Turkmenistan New Manat', '', '+993', 0),
('Turks and Caicos Islands', 'TC', 'US Dollar', '$', '+1', 0),
('Tuvalu', 'TV', 'Australian Dollar', '$', '+688', 0),
('Uganda', 'UG', 'Uganda Shilling', 'USh', '+256', 0),
('Ukraine', 'UA', 'Hryvnia', '₴', '+380', 0),
('United Arab Emirates', 'AE', 'UAE Dirham', '', '+971', 0),
('United Kingdom', 'GB', 'Pound Sterling', '£', '+44', 0),
('United States', 'US', 'US Dollar', '$', '+1', 0),
('United States Minor Outlying Islands', 'UM', 'US Dollar', '$', '+1', 0),
('Uruguay', 'UY', 'Peso Uruguayo', '$U', '+598', 0),
('Uzbekistan', 'UZ', 'Uzbekistan Sum', 'лв', '+998', 0),
('Vanuatu', 'VU', 'Vatu', '', '+678', 0),
('Venezuela, Bolivarian Republic of', 'VE', 'Bolivar', 'Bs', '+58', 0),
('Viet Nam', 'VN', 'Dong', '₫', '+84', 0),
('Virgin Islands, British', 'VG', 'US Dollar', '$', '+1', 0),
('Virgin Islands, U.S.', 'VI', 'US Dollar', '$', '+1', 0),
('Wallis and Futuna', 'WF', 'CFP Franc', '', '+681', 0),
('Western Sahara', 'EH', 'Moroccan Dirham', '', '+212', 0),
('Yemen', 'YE', 'Yemeni Rial', '﷼', '+967', 0),
('Zambia', 'ZM', 'Zambian Kwacha', '', '+260', 0),
('Zimbabwe', 'ZW', 'Zimbabwe Dollar', '', '+263', 0),
('Åland Islands', 'AX', 'Euro', '€', '+358', 0);

-- Create cities table
CREATE TABLE `cities` (
  `cityid` int(11) NOT NULL AUTO_INCREMENT,
  `cityname` varchar(100) NOT NULL,
  `countryid` int(11) NOT NULL,
  PRIMARY KEY (`cityid`),
  KEY `fk_cities_countries` (`countryid`),
  CONSTRAINT `fk_cities_countries` FOREIGN KEY (`countryid`) REFERENCES `countries` (`countryid`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Populate cities (Capitals and Major Hubs)
INSERT INTO `cities` (cityname, countryid) VALUES
('Kabul', (SELECT countryid FROM countries WHERE countrycode = 'AF' LIMIT 1)),
('Mariehamn', (SELECT countryid FROM countries WHERE countrycode = 'AX' LIMIT 1)),
('Tirana', (SELECT countryid FROM countries WHERE countrycode = 'AL' LIMIT 1)),
('Algiers', (SELECT countryid FROM countries WHERE countrycode = 'DZ' LIMIT 1)),
('Pago Pago', (SELECT countryid FROM countries WHERE countrycode = 'AS' LIMIT 1)),
('Andorra la Vella', (SELECT countryid FROM countries WHERE countrycode = 'AD' LIMIT 1)),
('Luanda', (SELECT countryid FROM countries WHERE countrycode = 'AO' LIMIT 1)),
('The Valley', (SELECT countryid FROM countries WHERE countrycode = 'AI' LIMIT 1)),
('Buenos Aires', (SELECT countryid FROM countries WHERE countrycode = 'AR' LIMIT 1)),
('Yerevan', (SELECT countryid FROM countries WHERE countrycode = 'AM' LIMIT 1)),
('Oranjestad', (SELECT countryid FROM countries WHERE countrycode = 'AW' LIMIT 1)),
('Canberra', (SELECT countryid FROM countries WHERE countrycode = 'AU' LIMIT 1)),
('Vienna', (SELECT countryid FROM countries WHERE countrycode = 'AT' LIMIT 1)),
('Baku', (SELECT countryid FROM countries WHERE countrycode = 'AZ' LIMIT 1)),
('Manama', (SELECT countryid FROM countries WHERE countrycode = 'BH' LIMIT 1)),
('Dhaka', (SELECT countryid FROM countries WHERE countrycode = 'BD' LIMIT 1)),
('Bridgetown', (SELECT countryid FROM countries WHERE countrycode = 'BB' LIMIT 1)),
('Minsk', (SELECT countryid FROM countries WHERE countrycode = 'BY' LIMIT 1)),
('Brussels', (SELECT countryid FROM countries WHERE countrycode = 'BE' LIMIT 1)),
('Belmopan', (SELECT countryid FROM countries WHERE countrycode = 'BZ' LIMIT 1)),
('Porto-Novo', (SELECT countryid FROM countries WHERE countrycode = 'BJ' LIMIT 1)),
('Hamilton', (SELECT countryid FROM countries WHERE countrycode = 'BM' LIMIT 1)),
('Thimphu', (SELECT countryid FROM countries WHERE countrycode = 'BT' LIMIT 1)),
('Sucre', (SELECT countryid FROM countries WHERE countrycode = 'BO' LIMIT 1)),
('Kralendijk', (SELECT countryid FROM countries WHERE countrycode = 'BQ' LIMIT 1)),
('Sarajevo', (SELECT countryid FROM countries WHERE countrycode = 'BA' LIMIT 1)),
('Gaborone', (SELECT countryid FROM countries WHERE countrycode = 'BW' LIMIT 1)),
('Brasilia', (SELECT countryid FROM countries WHERE countrycode = 'BR' LIMIT 1)),
('Diego Garcia', (SELECT countryid FROM countries WHERE countrycode = 'IO' LIMIT 1)),
('Bandar Seri Begawan', (SELECT countryid FROM countries WHERE countrycode = 'BN' LIMIT 1)),
('Sofia', (SELECT countryid FROM countries WHERE countrycode = 'BG' LIMIT 1)),
('Ouagadougou', (SELECT countryid FROM countries WHERE countrycode = 'BF' LIMIT 1)),
('Bujumbura', (SELECT countryid FROM countries WHERE countrycode = 'BI' LIMIT 1)),
('Phnom Penh', (SELECT countryid FROM countries WHERE countrycode = 'KH' LIMIT 1)),
('Yaounde', (SELECT countryid FROM countries WHERE countrycode = 'CM' LIMIT 1)),
('Ottawa', (SELECT countryid FROM countries WHERE countrycode = 'CA' LIMIT 1)),
('Praia', (SELECT countryid FROM countries WHERE countrycode = 'CV' LIMIT 1)),
('George Town', (SELECT countryid FROM countries WHERE countrycode = 'KY' LIMIT 1)),
('Bangui', (SELECT countryid FROM countries WHERE countrycode = 'CF' LIMIT 1)),
('Santiago', (SELECT countryid FROM countries WHERE countrycode = 'CL' LIMIT 1)),
('Beijing', (SELECT countryid FROM countries WHERE countrycode = 'CN' LIMIT 1)),
('Flying Fish Cove', (SELECT countryid FROM countries WHERE countrycode = 'CX' LIMIT 1)),
('West Island', (SELECT countryid FROM countries WHERE countrycode = 'CC' LIMIT 1)),
('Bogotá', (SELECT countryid FROM countries WHERE countrycode = 'CO' LIMIT 1)),
('Moroni', (SELECT countryid FROM countries WHERE countrycode = 'KM' LIMIT 1)),
('Brazzaville', (SELECT countryid FROM countries WHERE countrycode = 'CG' LIMIT 1)),
('Avarua', (SELECT countryid FROM countries WHERE countrycode = 'CK' LIMIT 1)),
('San Jose', (SELECT countryid FROM countries WHERE countrycode = 'CR' LIMIT 1)),
('Zagreb', (SELECT countryid FROM countries WHERE countrycode = 'HR' LIMIT 1)),
('Havana', (SELECT countryid FROM countries WHERE countrycode = 'CU' LIMIT 1)),
('Willemstad', (SELECT countryid FROM countries WHERE countrycode = 'CW' LIMIT 1)),
('Nicosia', (SELECT countryid FROM countries WHERE countrycode = 'CY' LIMIT 1)),
('Prague', (SELECT countryid FROM countries WHERE countrycode = 'CZ' LIMIT 1)),
('Kinshasa', (SELECT countryid FROM countries WHERE countrycode = 'CD' LIMIT 1)),
('Copenhagen', (SELECT countryid FROM countries WHERE countrycode = 'DK' LIMIT 1)),
('Djibouti', (SELECT countryid FROM countries WHERE countrycode = 'DJ' LIMIT 1)),
('Roseau', (SELECT countryid FROM countries WHERE countrycode = 'DM' LIMIT 1)),
('Santo Domingo', (SELECT countryid FROM countries WHERE countrycode = 'DO' LIMIT 1)),
('Quito', (SELECT countryid FROM countries WHERE countrycode = 'EC' LIMIT 1)),
('Cairo', (SELECT countryid FROM countries WHERE countrycode = 'EG' LIMIT 1)),
('San Salvador', (SELECT countryid FROM countries WHERE countrycode = 'SV' LIMIT 1)),
('Malabo', (SELECT countryid FROM countries WHERE countrycode = 'GQ' LIMIT 1)),
('Asmara', (SELECT countryid FROM countries WHERE countrycode = 'ER' LIMIT 1)),
('Tallinn', (SELECT countryid FROM countries WHERE countrycode = 'EE' LIMIT 1)),
('Mbabane', (SELECT countryid FROM countries WHERE countrycode = 'SZ' LIMIT 1)),
('Addis Ababa', (SELECT countryid FROM countries WHERE countrycode = 'ET' LIMIT 1)),
('Stanley', (SELECT countryid FROM countries WHERE countrycode = 'FK' LIMIT 1)),
('Torshavn', (SELECT countryid FROM countries WHERE countrycode = 'FO' LIMIT 1)),
('Suva', (SELECT countryid FROM countries WHERE countrycode = 'FJ' LIMIT 1)),
('Helsinki', (SELECT countryid FROM countries WHERE countrycode = 'FI' LIMIT 1)),
('Paris', (SELECT countryid FROM countries WHERE countrycode = 'FR' LIMIT 1)),
('Cayenne', (SELECT countryid FROM countries WHERE countrycode = 'GF' LIMIT 1)),
('Papeete', (SELECT countryid FROM countries WHERE countrycode = 'PF' LIMIT 1)),
('Port-aux-Francais', (SELECT countryid FROM countries WHERE countrycode = 'TF' LIMIT 1)),
('Libreville', (SELECT countryid FROM countries WHERE countrycode = 'GA' LIMIT 1)),
('Tbilisi', (SELECT countryid FROM countries WHERE countrycode = 'GE' LIMIT 1)),
('Berlin', (SELECT countryid FROM countries WHERE countrycode = 'DE' LIMIT 1)),
('Accra', (SELECT countryid FROM countries WHERE countrycode = 'GH' LIMIT 1)),
('Gibraltar', (SELECT countryid FROM countries WHERE countrycode = 'GI' LIMIT 1)),
('Athens', (SELECT countryid FROM countries WHERE countrycode = 'GR' LIMIT 1)),
('Nuuk', (SELECT countryid FROM countries WHERE countrycode = 'GL' LIMIT 1)),
('Basse-Terre', (SELECT countryid FROM countries WHERE countrycode = 'GP' LIMIT 1)),
('Hagatna', (SELECT countryid FROM countries WHERE countrycode = 'GU' LIMIT 1)),
('Guatemala City', (SELECT countryid FROM countries WHERE countrycode = 'GT' LIMIT 1)),
('St Peter Port', (SELECT countryid FROM countries WHERE countrycode = 'GG' LIMIT 1)),
('Conakry', (SELECT countryid FROM countries WHERE countrycode = 'GN' LIMIT 1)),
('Bissau', (SELECT countryid FROM countries WHERE countrycode = 'GW' LIMIT 1)),
('Georgetown', (SELECT countryid FROM countries WHERE countrycode = 'GY' LIMIT 1)),
('Port-au-Prince', (SELECT countryid FROM countries WHERE countrycode = 'HT' LIMIT 1)),
('Tegucigalpa', (SELECT countryid FROM countries WHERE countrycode = 'HN' LIMIT 1)),
('Hong Kong', (SELECT countryid FROM countries WHERE countrycode = 'HK' LIMIT 1)),
('Budapest', (SELECT countryid FROM countries WHERE countrycode = 'HU' LIMIT 1)),
('Reykjavik', (SELECT countryid FROM countries WHERE countrycode = 'IS' LIMIT 1)),
('New Delhi', (SELECT countryid FROM countries WHERE countrycode = 'IN' LIMIT 1)),
('Jakarta', (SELECT countryid FROM countries WHERE countrycode = 'ID' LIMIT 1)),
('Tehran', (SELECT countryid FROM countries WHERE countrycode = 'IR' LIMIT 1)),
('Baghdad', (SELECT countryid FROM countries WHERE countrycode = 'IQ' LIMIT 1)),
('Dublin', (SELECT countryid FROM countries WHERE countrycode = 'IE' LIMIT 1)),
('Jerusalem', (SELECT countryid FROM countries WHERE countrycode = 'IL' LIMIT 1)),
('Rome', (SELECT countryid FROM countries WHERE countrycode = 'IT' LIMIT 1)),
('Kingston', (SELECT countryid FROM countries WHERE countrycode = 'JM' LIMIT 1)),
('Tokyo', (SELECT countryid FROM countries WHERE countrycode = 'JP' LIMIT 1)),
('Saint Helier', (SELECT countryid FROM countries WHERE countrycode = 'JE' LIMIT 1)),
('Amman', (SELECT countryid FROM countries WHERE countrycode = 'JO' LIMIT 1)),
('Astana', (SELECT countryid FROM countries WHERE countrycode = 'KZ' LIMIT 1)),
('Nairobi', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Tarawa', (SELECT countryid FROM countries WHERE countrycode = 'KI' LIMIT 1)),
('Kuwait City', (SELECT countryid FROM countries WHERE countrycode = 'KW' LIMIT 1)),
('Bishkek', (SELECT countryid FROM countries WHERE countrycode = 'KG' LIMIT 1)),
('Riga', (SELECT countryid FROM countries WHERE countrycode = 'LV' LIMIT 1)),
('Beirut', (SELECT countryid FROM countries WHERE countrycode = 'LB' LIMIT 1)),
('Maseru', (SELECT countryid FROM countries WHERE countrycode = 'LS' LIMIT 1)),
('Monrovia', (SELECT countryid FROM countries WHERE countrycode = 'LR' LIMIT 1)),
('Tripolis', (SELECT countryid FROM countries WHERE countrycode = 'LY' LIMIT 1)),
('Vaduz', (SELECT countryid FROM countries WHERE countrycode = 'LI' LIMIT 1)),
('Vilnius', (SELECT countryid FROM countries WHERE countrycode = 'LT' LIMIT 1)),
('Luxembourg', (SELECT countryid FROM countries WHERE countrycode = 'LU' LIMIT 1)),
('Macao', (SELECT countryid FROM countries WHERE countrycode = 'MO' LIMIT 1)),
('Antananarivo', (SELECT countryid FROM countries WHERE countrycode = 'MG' LIMIT 1)),
('Lilongwe', (SELECT countryid FROM countries WHERE countrycode = 'MW' LIMIT 1)),
('Kuala Lumpur', (SELECT countryid FROM countries WHERE countrycode = 'MY' LIMIT 1)),
('Male', (SELECT countryid FROM countries WHERE countrycode = 'MV' LIMIT 1)),
('Bamako', (SELECT countryid FROM countries WHERE countrycode = 'ML' LIMIT 1)),
('Valletta', (SELECT countryid FROM countries WHERE countrycode = 'MT' LIMIT 1)),
('Douglas, Isle of Man', (SELECT countryid FROM countries WHERE countrycode = 'IM' LIMIT 1)),
('Majuro', (SELECT countryid FROM countries WHERE countrycode = 'MH' LIMIT 1)),
('Fort-de-France', (SELECT countryid FROM countries WHERE countrycode = 'MQ' LIMIT 1)),
('Nouakchott', (SELECT countryid FROM countries WHERE countrycode = 'MR' LIMIT 1)),
('Port Louis', (SELECT countryid FROM countries WHERE countrycode = 'MU' LIMIT 1)),
('Mamoudzou', (SELECT countryid FROM countries WHERE countrycode = 'YT' LIMIT 1)),
('Ciudad de México', (SELECT countryid FROM countries WHERE countrycode = 'MX' LIMIT 1)),
('Palikir', (SELECT countryid FROM countries WHERE countrycode = 'FM' LIMIT 1)),
('Chisinau', (SELECT countryid FROM countries WHERE countrycode = 'MD' LIMIT 1)),
('Monaco', (SELECT countryid FROM countries WHERE countrycode = 'MC' LIMIT 1)),
('Ulan Bator', (SELECT countryid FROM countries WHERE countrycode = 'MN' LIMIT 1)),
('Podgorica', (SELECT countryid FROM countries WHERE countrycode = 'ME' LIMIT 1)),
('Plymouth', (SELECT countryid FROM countries WHERE countrycode = 'MS' LIMIT 1)),
('Rabat', (SELECT countryid FROM countries WHERE countrycode = 'MA' LIMIT 1)),
('Maputo', (SELECT countryid FROM countries WHERE countrycode = 'MZ' LIMIT 1)),
('Nay Pyi Taw', (SELECT countryid FROM countries WHERE countrycode = 'MM' LIMIT 1)),
('Windhoek', (SELECT countryid FROM countries WHERE countrycode = 'NA' LIMIT 1)),
('Yaren', (SELECT countryid FROM countries WHERE countrycode = 'NR' LIMIT 1)),
('Kathmandu', (SELECT countryid FROM countries WHERE countrycode = 'NP' LIMIT 1)),
('Amsterdam', (SELECT countryid FROM countries WHERE countrycode = 'NL' LIMIT 1)),
('Noumea', (SELECT countryid FROM countries WHERE countrycode = 'NC' LIMIT 1)),
('Wellington', (SELECT countryid FROM countries WHERE countrycode = 'NZ' LIMIT 1)),
('Managua', (SELECT countryid FROM countries WHERE countrycode = 'NI' LIMIT 1)),
('Niamey', (SELECT countryid FROM countries WHERE countrycode = 'NE' LIMIT 1)),
('Abuja', (SELECT countryid FROM countries WHERE countrycode = 'NG' LIMIT 1)),
('Alofi', (SELECT countryid FROM countries WHERE countrycode = 'NU' LIMIT 1)),
('Kingston', (SELECT countryid FROM countries WHERE countrycode = 'NF' LIMIT 1)),
('Skopje', (SELECT countryid FROM countries WHERE countrycode = 'MK' LIMIT 1)),
('Saipan', (SELECT countryid FROM countries WHERE countrycode = 'MP' LIMIT 1)),
('Oslo', (SELECT countryid FROM countries WHERE countrycode = 'NO' LIMIT 1)),
('Muscat', (SELECT countryid FROM countries WHERE countrycode = 'OM' LIMIT 1)),
('Islamabad', (SELECT countryid FROM countries WHERE countrycode = 'PK' LIMIT 1)),
('Melekeok', (SELECT countryid FROM countries WHERE countrycode = 'PW' LIMIT 1)),
('East Jerusalem', (SELECT countryid FROM countries WHERE countrycode = 'PS' LIMIT 1)),
('Panama City', (SELECT countryid FROM countries WHERE countrycode = 'PA' LIMIT 1)),
('Port Moresby', (SELECT countryid FROM countries WHERE countrycode = 'PG' LIMIT 1)),
('Asunción', (SELECT countryid FROM countries WHERE countrycode = 'PY' LIMIT 1)),
('Lima', (SELECT countryid FROM countries WHERE countrycode = 'PE' LIMIT 1)),
('Manila', (SELECT countryid FROM countries WHERE countrycode = 'PH' LIMIT 1)),
('Adamstown', (SELECT countryid FROM countries WHERE countrycode = 'PN' LIMIT 1)),
('Warsaw', (SELECT countryid FROM countries WHERE countrycode = 'PL' LIMIT 1)),
('Lisbon', (SELECT countryid FROM countries WHERE countrycode = 'PT' LIMIT 1)),
('San Juan', (SELECT countryid FROM countries WHERE countrycode = 'PR' LIMIT 1)),
('Doha', (SELECT countryid FROM countries WHERE countrycode = 'QA' LIMIT 1)),
('Saint-Denis', (SELECT countryid FROM countries WHERE countrycode = 'RE' LIMIT 1)),
('Bucharest', (SELECT countryid FROM countries WHERE countrycode = 'RO' LIMIT 1)),
('Moscow', (SELECT countryid FROM countries WHERE countrycode = 'RU' LIMIT 1)),
('Kigali', (SELECT countryid FROM countries WHERE countrycode = 'RW' LIMIT 1)),
('Jamestown', (SELECT countryid FROM countries WHERE countrycode = 'SH' LIMIT 1)),
('Basseterre', (SELECT countryid FROM countries WHERE countrycode = 'KN' LIMIT 1)),
('Castries', (SELECT countryid FROM countries WHERE countrycode = 'LC' LIMIT 1)),
('Saint-Pierre', (SELECT countryid FROM countries WHERE countrycode = 'PM' LIMIT 1)),
('Kingstown', (SELECT countryid FROM countries WHERE countrycode = 'VC' LIMIT 1)),
('Gustavia', (SELECT countryid FROM countries WHERE countrycode = 'BL' LIMIT 1)),
('Marigot', (SELECT countryid FROM countries WHERE countrycode = 'MF' LIMIT 1)),
('Apia', (SELECT countryid FROM countries WHERE countrycode = 'WS' LIMIT 1)),
('San Marino', (SELECT countryid FROM countries WHERE countrycode = 'SM' LIMIT 1)),
('Sao Tome', (SELECT countryid FROM countries WHERE countrycode = 'ST' LIMIT 1)),
('Riyadh', (SELECT countryid FROM countries WHERE countrycode = 'SA' LIMIT 1)),
('Dakar', (SELECT countryid FROM countries WHERE countrycode = 'SN' LIMIT 1)),
('Belgrade', (SELECT countryid FROM countries WHERE countrycode = 'RS' LIMIT 1)),
('Victoria', (SELECT countryid FROM countries WHERE countrycode = 'SC' LIMIT 1)),
('Freetown', (SELECT countryid FROM countries WHERE countrycode = 'SL' LIMIT 1)),
('Singapur', (SELECT countryid FROM countries WHERE countrycode = 'SG' LIMIT 1)),
('Philipsburg', (SELECT countryid FROM countries WHERE countrycode = 'SX' LIMIT 1)),
('Bratislava', (SELECT countryid FROM countries WHERE countrycode = 'SK' LIMIT 1)),
('Ljubljana', (SELECT countryid FROM countries WHERE countrycode = 'SI' LIMIT 1)),
('Honiara', (SELECT countryid FROM countries WHERE countrycode = 'SB' LIMIT 1)),
('Mogadishu', (SELECT countryid FROM countries WHERE countrycode = 'SO' LIMIT 1)),
('Pretoria', (SELECT countryid FROM countries WHERE countrycode = 'ZA' LIMIT 1)),
('Grytviken', (SELECT countryid FROM countries WHERE countrycode = 'GS' LIMIT 1)),
('Seoul', (SELECT countryid FROM countries WHERE countrycode = 'KR' LIMIT 1)),
('Juba', (SELECT countryid FROM countries WHERE countrycode = 'SS' LIMIT 1)),
('Madrid', (SELECT countryid FROM countries WHERE countrycode = 'ES' LIMIT 1)),
('Colombo', (SELECT countryid FROM countries WHERE countrycode = 'LK' LIMIT 1)),
('Khartoum', (SELECT countryid FROM countries WHERE countrycode = 'SD' LIMIT 1)),
('Paramaribo', (SELECT countryid FROM countries WHERE countrycode = 'SR' LIMIT 1)),
('Longyearbyen', (SELECT countryid FROM countries WHERE countrycode = 'SJ' LIMIT 1)),
('Stockholm', (SELECT countryid FROM countries WHERE countrycode = 'SE' LIMIT 1)),
('Bern', (SELECT countryid FROM countries WHERE countrycode = 'CH' LIMIT 1)),
('Damascus', (SELECT countryid FROM countries WHERE countrycode = 'SY' LIMIT 1)),
('Taipei', (SELECT countryid FROM countries WHERE countrycode = 'TW' LIMIT 1)),
('Dushanbe', (SELECT countryid FROM countries WHERE countrycode = 'TJ' LIMIT 1)),
('Dodoma', (SELECT countryid FROM countries WHERE countrycode = 'TZ' LIMIT 1)),
('Bangkok', (SELECT countryid FROM countries WHERE countrycode = 'TH' LIMIT 1)),
('Nassau', (SELECT countryid FROM countries WHERE countrycode = 'BS' LIMIT 1)),
('Banjul', (SELECT countryid FROM countries WHERE countrycode = 'GM' LIMIT 1)),
('Dili', (SELECT countryid FROM countries WHERE countrycode = 'TL' LIMIT 1)),
('Lome', (SELECT countryid FROM countries WHERE countrycode = 'TG' LIMIT 1)),
('Port of Spain', (SELECT countryid FROM countries WHERE countrycode = 'TT' LIMIT 1)),
('Tunis', (SELECT countryid FROM countries WHERE countrycode = 'TN' LIMIT 1)),
('Ankara', (SELECT countryid FROM countries WHERE countrycode = 'TR' LIMIT 1)),
('Ashgabat', (SELECT countryid FROM countries WHERE countrycode = 'TM' LIMIT 1)),
('Cockburn Town', (SELECT countryid FROM countries WHERE countrycode = 'TC' LIMIT 1)),
('Funafuti', (SELECT countryid FROM countries WHERE countrycode = 'TV' LIMIT 1)),
('Kampala', (SELECT countryid FROM countries WHERE countrycode = 'UG' LIMIT 1)),
('Kyiv', (SELECT countryid FROM countries WHERE countrycode = 'UA' LIMIT 1)),
('Abu Dhabi', (SELECT countryid FROM countries WHERE countrycode = 'AE' LIMIT 1)),
('London', (SELECT countryid FROM countries WHERE countrycode = 'GB' LIMIT 1)),
('Washington', (SELECT countryid FROM countries WHERE countrycode = 'US' LIMIT 1)),
('Montevideo', (SELECT countryid FROM countries WHERE countrycode = 'UY' LIMIT 1)),
('Tashkent', (SELECT countryid FROM countries WHERE countrycode = 'UZ' LIMIT 1)),
('Port Vila', (SELECT countryid FROM countries WHERE countrycode = 'VU' LIMIT 1)),
('Vatican City', (SELECT countryid FROM countries WHERE countrycode = 'VA' LIMIT 1)),
('Caracas', (SELECT countryid FROM countries WHERE countrycode = 'VE' LIMIT 1)),
('Hanoi', (SELECT countryid FROM countries WHERE countrycode = 'VN' LIMIT 1)),
('Road Town', (SELECT countryid FROM countries WHERE countrycode = 'VG' LIMIT 1)),
('Charlotte Amalie', (SELECT countryid FROM countries WHERE countrycode = 'VI' LIMIT 1)),
('Mata Utu', (SELECT countryid FROM countries WHERE countrycode = 'WF' LIMIT 1)),
('El-Aaiun', (SELECT countryid FROM countries WHERE countrycode = 'EH' LIMIT 1)),
('Sanaa', (SELECT countryid FROM countries WHERE countrycode = 'YE' LIMIT 1)),
('Lusaka', (SELECT countryid FROM countries WHERE countrycode = 'ZM' LIMIT 1)),
('Harare', (SELECT countryid FROM countries WHERE countrycode = 'ZW' LIMIT 1)),
('Mombasa', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kisumu', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Nakuru', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Eldoret', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Thika', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Malindi', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kitale', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Garissa', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kakamega', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Machakos', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Lamu', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Nanyuki', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Voi', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kericho', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Nyeri', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Dar es Salaam', (SELECT countryid FROM countries WHERE countrycode = 'TZ' LIMIT 1)),
('Mwanza', (SELECT countryid FROM countries WHERE countrycode = 'TZ' LIMIT 1)),
('Arusha', (SELECT countryid FROM countries WHERE countrycode = 'TZ' LIMIT 1)),
('Mbeya', (SELECT countryid FROM countries WHERE countrycode = 'TZ' LIMIT 1)),
('Tanga', (SELECT countryid FROM countries WHERE countrycode = 'TZ' LIMIT 1)),
('Tabora', (SELECT countryid FROM countries WHERE countrycode = 'TZ' LIMIT 1)),
('Morogoro', (SELECT countryid FROM countries WHERE countrycode = 'TZ' LIMIT 1)),
('Kigoma', (SELECT countryid FROM countries WHERE countrycode = 'TZ' LIMIT 1)),
('Iringa', (SELECT countryid FROM countries WHERE countrycode = 'TZ' LIMIT 1)),
('Gulu', (SELECT countryid FROM countries WHERE countrycode = 'UG' LIMIT 1)),
('Lira', (SELECT countryid FROM countries WHERE countrycode = 'UG' LIMIT 1)),
('Jinja', (SELECT countryid FROM countries WHERE countrycode = 'UG' LIMIT 1)),
('Mbarara', (SELECT countryid FROM countries WHERE countrycode = 'UG' LIMIT 1)),
('Mbale', (SELECT countryid FROM countries WHERE countrycode = 'UG' LIMIT 1)),
('Masaka', (SELECT countryid FROM countries WHERE countrycode = 'UG' LIMIT 1)),
('Entebbe', (SELECT countryid FROM countries WHERE countrycode = 'UG' LIMIT 1)),
('Hoima', (SELECT countryid FROM countries WHERE countrycode = 'UG' LIMIT 1)),
('Fort Portal', (SELECT countryid FROM countries WHERE countrycode = 'UG' LIMIT 1)),
('Butare', (SELECT countryid FROM countries WHERE countrycode = 'RW' LIMIT 1)),
('Gisenyi', (SELECT countryid FROM countries WHERE countrycode = 'RW' LIMIT 1)),
('Musanze', (SELECT countryid FROM countries WHERE countrycode = 'RW' LIMIT 1)),
('Kayonza', (SELECT countryid FROM countries WHERE countrycode = 'RW' LIMIT 1)),
('Kibuye', (SELECT countryid FROM countries WHERE countrycode = 'RW' LIMIT 1)),
('Gitega', (SELECT countryid FROM countries WHERE countrycode = 'BI' LIMIT 1)),
('Muyinga', (SELECT countryid FROM countries WHERE countrycode = 'BI' LIMIT 1)),
('Ngozi', (SELECT countryid FROM countries WHERE countrycode = 'BI' LIMIT 1)),
('Rumonge', (SELECT countryid FROM countries WHERE countrycode = 'BI' LIMIT 1)),
('Malakal', (SELECT countryid FROM countries WHERE countrycode = 'SS' LIMIT 1)),
('Wau', (SELECT countryid FROM countries WHERE countrycode = 'SS' LIMIT 1)),
('Yei', (SELECT countryid FROM countries WHERE countrycode = 'SS' LIMIT 1)),
('Yambio', (SELECT countryid FROM countries WHERE countrycode = 'SS' LIMIT 1)),
('Bor', (SELECT countryid FROM countries WHERE countrycode = 'SS' LIMIT 1)),
('Lubumbashi', (SELECT countryid FROM countries WHERE countrycode = 'CD' LIMIT 1)),
('Goma', (SELECT countryid FROM countries WHERE countrycode = 'CD' LIMIT 1)),
('Bukavu', (SELECT countryid FROM countries WHERE countrycode = 'CD' LIMIT 1)),
('Kisangani', (SELECT countryid FROM countries WHERE countrycode = 'CD' LIMIT 1)),
('Matadi', (SELECT countryid FROM countries WHERE countrycode = 'CD' LIMIT 1)),
('Kikwit', (SELECT countryid FROM countries WHERE countrycode = 'CD' LIMIT 1)),
('Kananga', (SELECT countryid FROM countries WHERE countrycode = 'CD' LIMIT 1)),
('Kolwezi', (SELECT countryid FROM countries WHERE countrycode = 'CD' LIMIT 1)),
('Hargeisa', (SELECT countryid FROM countries WHERE countrycode = 'SO' LIMIT 1)),
('Bosaso', (SELECT countryid FROM countries WHERE countrycode = 'SO' LIMIT 1)),
('Baidoa', (SELECT countryid FROM countries WHERE countrycode = 'SO' LIMIT 1)),
('Kismayo', (SELECT countryid FROM countries WHERE countrycode = 'SO' LIMIT 1)),
('Merca', (SELECT countryid FROM countries WHERE countrycode = 'SO' LIMIT 1)),
('Berbera', (SELECT countryid FROM countries WHERE countrycode = 'SO' LIMIT 1)),
('Galkayo', (SELECT countryid FROM countries WHERE countrycode = 'SO' LIMIT 1)),
('New York', (SELECT countryid FROM countries WHERE countrycode = 'US' LIMIT 1)),
('Los Angeles', (SELECT countryid FROM countries WHERE countrycode = 'US' LIMIT 1)),
('Chicago', (SELECT countryid FROM countries WHERE countrycode = 'US' LIMIT 1)),
('Houston', (SELECT countryid FROM countries WHERE countrycode = 'US' LIMIT 1)),
('Phoenix', (SELECT countryid FROM countries WHERE countrycode = 'US' LIMIT 1)),
('Philadelphia', (SELECT countryid FROM countries WHERE countrycode = 'US' LIMIT 1)),
('San Antonio', (SELECT countryid FROM countries WHERE countrycode = 'US' LIMIT 1)),
('San Diego', (SELECT countryid FROM countries WHERE countrycode = 'US' LIMIT 1)),
('Dallas', (SELECT countryid FROM countries WHERE countrycode = 'US' LIMIT 1)),
('Birmingham', (SELECT countryid FROM countries WHERE countrycode = 'GB' LIMIT 1)),
('Manchester', (SELECT countryid FROM countries WHERE countrycode = 'GB' LIMIT 1)),
('Glasgow', (SELECT countryid FROM countries WHERE countrycode = 'GB' LIMIT 1)),
('Liverpool', (SELECT countryid FROM countries WHERE countrycode = 'GB' LIMIT 1)),
('Edinburgh', (SELECT countryid FROM countries WHERE countrycode = 'GB' LIMIT 1)),
('Mumbai', (SELECT countryid FROM countries WHERE countrycode = 'IN' LIMIT 1)),
('Bangalore', (SELECT countryid FROM countries WHERE countrycode = 'IN' LIMIT 1)),
('Hyderabad', (SELECT countryid FROM countries WHERE countrycode = 'IN' LIMIT 1)),
('Chennai', (SELECT countryid FROM countries WHERE countrycode = 'IN' LIMIT 1)),
('Kolkata', (SELECT countryid FROM countries WHERE countrycode = 'IN' LIMIT 1)),
('Pune', (SELECT countryid FROM countries WHERE countrycode = 'IN' LIMIT 1)),
('Shanghai', (SELECT countryid FROM countries WHERE countrycode = 'CN' LIMIT 1)),
('Guangzhou', (SELECT countryid FROM countries WHERE countrycode = 'CN' LIMIT 1)),
('Shenzhen', (SELECT countryid FROM countries WHERE countrycode = 'CN' LIMIT 1)),
('Tianjin', (SELECT countryid FROM countries WHERE countrycode = 'CN' LIMIT 1)),
('Chengdu', (SELECT countryid FROM countries WHERE countrycode = 'CN' LIMIT 1)),
('Wuhan', (SELECT countryid FROM countries WHERE countrycode = 'CN' LIMIT 1)),
('Berlin', (SELECT countryid FROM countries WHERE countrycode = 'DE' LIMIT 1)),
('Munich', (SELECT countryid FROM countries WHERE countrycode = 'DE' LIMIT 1)),
('Hamburg', (SELECT countryid FROM countries WHERE countrycode = 'DE' LIMIT 1)),
('Frankfurt', (SELECT countryid FROM countries WHERE countrycode = 'DE' LIMIT 1)),
('Lyon', (SELECT countryid FROM countries WHERE countrycode = 'FR' LIMIT 1)),
('Marseille', (SELECT countryid FROM countries WHERE countrycode = 'FR' LIMIT 1)),
('Barcelona', (SELECT countryid FROM countries WHERE countrycode = 'ES' LIMIT 1)),
('Seville', (SELECT countryid FROM countries WHERE countrycode = 'ES' LIMIT 1)),
('Milan', (SELECT countryid FROM countries WHERE countrycode = 'IT' LIMIT 1)),
('Naples', (SELECT countryid FROM countries WHERE countrycode = 'IT' LIMIT 1)),
('Venice', (SELECT countryid FROM countries WHERE countrycode = 'IT' LIMIT 1)),
('Amsterdam', (SELECT countryid FROM countries WHERE countrycode = 'NL' LIMIT 1)),
('Rotterdam', (SELECT countryid FROM countries WHERE countrycode = 'NL' LIMIT 1)),
('Zurich', (SELECT countryid FROM countries WHERE countrycode = 'CH' LIMIT 1)),
('Geneva', (SELECT countryid FROM countries WHERE countrycode = 'CH' LIMIT 1)),
('Toronto', (SELECT countryid FROM countries WHERE countrycode = 'CA' LIMIT 1)),
('Montreal', (SELECT countryid FROM countries WHERE countrycode = 'CA' LIMIT 1)),
('Vancouver', (SELECT countryid FROM countries WHERE countrycode = 'CA' LIMIT 1)),
('Sydney', (SELECT countryid FROM countries WHERE countrycode = 'AU' LIMIT 1)),
('Melbourne', (SELECT countryid FROM countries WHERE countrycode = 'AU' LIMIT 1)),
('Auckland', (SELECT countryid FROM countries WHERE countrycode = 'NZ' LIMIT 1)),
('Dubai', (SELECT countryid FROM countries WHERE countrycode = 'AE' LIMIT 1)),
('Abu Dhabi', (SELECT countryid FROM countries WHERE countrycode = 'AE' LIMIT 1)),
('Jeddah', (SELECT countryid FROM countries WHERE countrycode = 'SA' LIMIT 1)),
('Sao Paulo', (SELECT countryid FROM countries WHERE countrycode = 'BR' LIMIT 1)),
('Rio de Janeiro', (SELECT countryid FROM countries WHERE countrycode = 'BR' LIMIT 1)),
('Istanbul', (SELECT countryid FROM countries WHERE countrycode = 'TR' LIMIT 1)),
('Seoul', (SELECT countryid FROM countries WHERE countrycode = 'KR' LIMIT 1)),
('Singapore', (SELECT countryid FROM countries WHERE countrycode = 'SG' LIMIT 1)),
('Ruiru', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kikuyu', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kiambu', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Limuru', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Ngong', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Athi River', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Juja', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kitengela', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kiserian', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Ongata Rongai', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Naivasha', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Bungoma', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Mumias', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Webuye', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kapsabet', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Nyahururu', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Lodwar', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kilifi', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Ukunda', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Meru', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Embu', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Isiolo', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Moyale', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Marsabit', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Wajir', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Mandera', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kisii', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Homa Bay', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Migori', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Siaya', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kerugoya', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kutus', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Karatina', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Bomet', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Narok', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kajiado', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kitui', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Taveta', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Mariakani', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kwale', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Diani', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Msambweni', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Hola', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Garsen', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Chuka', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Iten', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kabarnet', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Maralal', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1)),
('Kapenguria', (SELECT countryid FROM countries WHERE countrycode = 'KE' LIMIT 1));

-- CRUD Stored Procedures
DELIMITER $$

DROP PROCEDURE IF EXISTS `spgetcountries` $$
CREATE PROCEDURE `spgetcountries`()
BEGIN
    SELECT * FROM countries 
    ORDER BY isdefault DESC, countryname ASC;
END $$

DROP PROCEDURE IF EXISTS `spsavecountry` $$
CREATE PROCEDURE `spsavecountry`(
    IN $countryid INT,
    IN $countryname VARCHAR(100),
    IN $countrycode VARCHAR(10),
    IN $currency VARCHAR(50),
    IN $currencysymbol VARCHAR(10),
    IN $dialingcode VARCHAR(10),
    IN $isdefault TINYINT
)
BEGIN
    -- If setting as default, unset others
    IF $isdefault = 1 THEN
        UPDATE countries SET isdefault = 0;
    END IF;

    IF $countryid = 0 THEN
        INSERT INTO countries (countryname, countrycode, currency, currencysymbol, dialingcode, isdefault)
        VALUES ($countryname, $countrycode, $currency, $currencysymbol, $dialingcode, $isdefault);
    ELSE
        UPDATE countries SET 
            countryname = $countryname,
            countrycode = $countrycode,
            currency = $currency,
            currencysymbol = $currencysymbol,
            dialingcode = $dialingcode,
            isdefault = $isdefault
        WHERE countryid = $countryid;
    END IF;
END $$

DROP PROCEDURE IF EXISTS `spdeletecountry` $$
CREATE PROCEDURE `spdeletecountry`(IN $countryid INT)
BEGIN
    DELETE FROM countries WHERE countryid = $countryid;
END $$

-- City Procedures
DROP PROCEDURE IF EXISTS `spgetcities` $$
CREATE PROCEDURE `spgetcities`(IN $countryid INT)
BEGIN
    IF $countryid = 0 THEN
        SELECT c.*, co.countryname 
        FROM cities c
        JOIN countries co ON c.countryid = co.countryid
        ORDER BY co.countryname ASC, c.cityname ASC;
    ELSE
        SELECT * FROM cities 
        WHERE countryid = $countryid
        ORDER BY cityname ASC;
    END IF;
END $$

DROP PROCEDURE IF EXISTS `spsavecity` $$
CREATE PROCEDURE `spsavecity`(
    IN $cityid INT,
    IN $cityname VARCHAR(100),
    IN $countryid INT
)
BEGIN
    IF $cityid = 0 THEN
        INSERT INTO cities (cityname, countryid)
        VALUES ($cityname, $countryid);
    ELSE
        UPDATE cities SET 
            cityname = $cityname,
            countryid = $countryid
        WHERE cityid = $cityid;
    END IF;
END $$

DROP PROCEDURE IF EXISTS `spdeletecity` $$
CREATE PROCEDURE `spdeletecity`(IN $cityid INT)
BEGIN
    DELETE FROM cities WHERE cityid = $cityid;
END $$

DELIMITER ;
