<?php
    require_once("../models/reports.php");
    $report= new report();
    if(isset($_GET['getproductsalessummary'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $product=$_GET['product'];
        $report->getProductSalesSummary($startdate,$enddate,$product);
    }

    if(isset($_GET['profitabilityreport'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $posid=$_GET['posid'];
        $report->getProfitabilityReport($startdate,$enddate,$posid);
    }
    
    if(isset($_GET['posstocksummary'])){
        $asatdate=$_GET['asatdate'];
        $posid=$_GET['posid'];
        $report->getPOSStockSummary($posid,$asatdate);
    }
    if(isset($_GET['getstocksheet'])){
        $asatdate=$_GET['asatdate'];
        $report->getStockSheet($asatdate);
    }
    if(isset($_GET['getglstatement'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $accountid=$_GET['accountid'];
        $report->getGLStatement($startdate,$enddate,$accountid);
    }
    if(isset($_GET['getaccountspayableaginganalysis'])){
        $basedate=$_GET['basedate'];
        $report->getAccountsPayableAging($basedate);
    }
    if(isset($_GET['getaccountsreceivableaginganalysis'])){
        $basedate=$_GET['basedate'];
        $report->getAccountsReceivableAgingAnlysis($basedate);
    }
    if(isset($_GET['getcustomerstatement']) && isset($_GET['customerid']) && !empty($_GET['customerid'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $customerid=$_GET['customerid'];
        $report->getCustomerStatement($customerid,$startdate,$enddate);
    }
    if(isset($_GET['getcustomeraginganalysis']) && isset($_GET['customerid']) && !empty($_GET['customerid'])){
        $basedate=$_GET['basedate'];
        $customerid=$_GET['customerid'];
        $report->getCustomerAgingAnalysis($customerid,$basedate);

    }
    if(isset($_GET['getsupplierstatement'])){
        $supplierid=$_GET['supplierid'];
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $report->getSupplierStatement($supplierid,$startdate,$enddate);
    }
    if(isset($_GET['getsupplieraginganalysis'])){
        $supplierid=$_GET['supplierid'];
        $basedate=$_GET['basedate'];
        $report->getSupplierAgingAnalysis($basedate,$supplierid);
    }
    if(isset($_GET['gettrialbalance'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $report->getTrialBalance($startdate,$enddate);
    }
    if(isset($_GET['getprofitandlossaccount'])){
        $startdate =$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $report-> getProfitAndLossAccount($startdate,$enddate);
    }
    if(isset($_GET['getbalancesheet'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $report->getBalanceSheet($startdate,$enddate);
    }
    if(isset($_GET['getsalestrend'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $range=$_GET['range'];
        if(!isset($_GET['all'])){
            $userid=0;
        }else{
            $userid=$_GET['all']==1?0:$_SESSION['userid'];
        }
        $report->getsalestrend($startdate,$enddate,$range,$userid);
    }
    if(isset($_GET['getsalesbyquantity'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $range=$_GET['range'];
        if(!isset($_GET['all'])){
            $userid=0;
        }else{
            $userid=$_GET['all']==1?0:$_SESSION['userid'];
        }
        $report->getsalesbyquantity($startdate,$enddate,$range,$userid);
    }
    if(isset($_GET['getsalesbypaymentmode'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        if(!isset($_GET['all'])){
            $userid=0;
        }else{
            $userid=$_GET['all']==1?0:$_SESSION['userid'];
        }
        $report->getsalesbypaymentmode($startdate,$enddate,$userid);
    }
    if(isset($_GET['getsalesbycustomercount'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $range=$_GET['range'];
        $report->getsalesbycustomercount($startdate,$enddate,$range);
    }
    if(isset($_GET['getsalesbyoutlet'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $report->getsalesbyoutlet($startdate,$enddate);
    }
    if(isset($_GET['getsalesbysalesperson'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $report->getsalesbysalesperson($startdate,$enddate);
    }
    if(isset($_GET['getbestsellingproduct'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        if(!isset($_GET['all'])){
            $userid=0;
        }else{
            $userid=$_GET['all']==1?0:$_SESSION['userid'];
        }
        $report->getbestsellingproduct($startdate,$enddate,$userid);
    }
    if(isset($_GET['getbestsellingcategory'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $report->getbestsellingcategory($startdate,$enddate);
    }
    if(isset($_GET['getsalesbycustomervalue'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $daterange=$_GET['range'];
        $report->getsalesbycustomervalue($startdate,$enddate,$daterange);
    }
    if(isset($_GET['getcustomerperformance'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $report->getcustomerperformance($startdate,$enddate);
    }
    if(isset($_GET['getdashboardheader'])){
        $date=$_GET['date'];
        $report->getdashboardheader($date);
    }
    if(isset($_GET['gettransfers'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $source=$_GET['source'];
        $sourceid=$_GET['sourceid'];
        $destination=$_GET['destination'];
        $destinationid=$_GET['destinationid'];
        $report->gettransfers($source,$sourceid,$destination,$destinationid,$startdate,$enddate);
    }
    if(isset($_GET['geteaxpanedesalesbypaymentmethod'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $all=$_GET['all'];
        $userid=$all==1?0:$_SESSION['userid'];
        $report->getexpandedsalesbypaymentmethod($startdate,$enddate,$userid);
    }
    if(isset($_GET['getprofitandlossaccountheaders'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $report->getprofitandlossaccountheaders($startdate,$enddate);
    }
    if(isset($_GET['getprofitandlossaccountdetails'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $report->getprofitandlossaccountdetails($startdate,$enddate);
    }
    if(isset($_GET['getdiscountreport'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        $report->getdiscountreport($startdate,$enddate);
    }
    if(isset($_GET['getmasterstocksheet'])){
        $enddate=$_GET['enddate'];
        $report->getmasterstocksheet($enddate);
    }
    if(isset($_GET['getreturnoutwardssummary'])){
        $asatdate=$_GET['asatdate'];
        echo $report->getreturnoutwardssummary($asatdate);
    }

    if(isset($_GET['getreturninwardssummary'])){
        $asatdate=$_GET['asatdate'];
        echo $report->getreturninwardssummary($asatdate);
    }

    if(isset($_GET['productreport'])){
        $reportname=$_GET['productreport'];
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        if($reportname=="getproductpurchasessummary"){
            echo $report->getproductpurchasessummaryreport($startdate,$enddate);
        }else{
             echo $report->getproductsalessummaryreport($startdate,$enddate);
        }
    }
    if(isset($_GET['gettransferitemsreport'])){
        $cat=$_GET['cat'];
        $id=$_GET['id'];
        $startdate=$_GET['datefrom'];
        $enddate=$_GET['dateto'];
        echo $report->gettransferitemsreport($cat,$id,$startdate,$enddate);
    }

    if(isset($_GET['getstockmovementreport'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        echo $report->getinputoutputvatreport($startdate,$enddate);
    }

    if(isset($_GET['getinputoutputvatreport'])){
        $startdate=$_GET['startdate'];
        $enddate=$_GET['enddate'];
        echo $report->getinputoutputvatreport($startdate,$enddate);
    }

?>