INSERT INTO `countries` (countryname, countrycode, currency, currencysymbol, dialingcode, isdefault) VALUES
('Afghanistan', 'AF', 'Afghani', '؋', '+93', 0),
('Albania', 'AL', 'Lek', 'Lek', '+355', 0),
('Algeria', 'DZ', 'Algerian Dinar', '', '+213', 0),
('American Samoa', 'AS', 'US Dollar', '$', '+1', 0),
('Andorra', 'AD', 'Euro', '€', '+376', 0),
('Angola', 'AO', 'Kwanza', '', '+244', 0),
('Anguilla', 'AI', 'East Caribbean Dollar', '$', '+1', 0),
('Antarctica', 'AQ', '', '', '+672', 0),
('Antigua and Barbuda', 'AG', 'East Caribbean Dollar', '$', '+1', 0),
('Argentina', 'AR', 'Argentine Peso', '$', '+54', 0),
('Armenia', 'AM', 'Armenian Dram', '', '+374', 0),
('Aruba', 'AW', 'Aruban Florin', 'ƒ', '+297', 0),
('Australia', 'AU', 'Australian Dollar', '$', '+61', 0),
('Austria', 'AT', 'Euro', '€', '+43', 0),
('Azerbaijan', 'AZ', 'Azerbaijanian Manat', 'ман', '+994', 0),
('Bahamas', 'BS', 'Bahamian Dollar', '$', '+1', 0),
('Bahrain', 'BH', 'Bahraini Dinar', '', '+973', 0),
('Bangladesh', 'BD', 'Taka', '', '+880', 0),
('Barbados', 'BB', 'Barbados Dollar', '$', '+1', 0),
('Belarus', 'BY', 'Belarussian Ruble', 'p.', '+375', 0),
('Belgium', 'BE', 'Euro', '€', '+32', 0),
('Belize', 'BZ', 'Belize Dollar', 'BZ$', '+501', 0),
('Benin', 'BJ', 'CFA Franc BCEAO', '', '+229', 0),
('Bermuda', 'BM', 'Bermudian Dollar', '$', '+1', 0),
('Bhutan', 'BT', 'Indian Rupee', '₹', '+975', 0),
('Bolivia, Plurinational State of', 'BO', 'Boliviano', '$b', '+591', 0),
('Bonaire, Sint Eustatius and Saba', 'BQ', 'US Dollar', '$', '+599', 0),
('Bosnia and Herzegovina', 'BA', 'Convertible Mark', 'KM', '+387', 0),
('Botswana', 'BW', 'Pula', 'P', '+267', 0),
('Bouvet Island', 'BV', 'Norwegian Krone', 'kr', '+47', 0),
('Brazil', 'BR', 'Brazilian Real', 'R$', '+55', 0),
('British Indian Ocean Territory', 'IO', 'US Dollar', '$', '+246', 0),
('Brunei Darussalam', 'BN', 'Brunei Dollar', '$', '+673', 0),
('Bulgaria', 'BG', 'Bulgarian Lev', 'лв', '+359', 0),
('Burkina Faso', 'BF', 'CFA Franc BCEAO', '', '+226', 0),
('Burundi', 'BI', 'Burundi Franc', 'FBu', '+257', 0),
('Cambodia', 'KH', 'Riel', '៛', '+855', 0),
('Cameroon', 'CM', 'CFA Franc BEAC', '', '+237', 0),
('Canada', 'CA', 'Canadian Dollar', '$', '+1', 0),
('Cape Verde', 'CV', 'Cabo Verde Escudo', '', '+238', 0),
('Cayman Islands', 'KY', 'Cayman Islands Dollar', '$', '+1', 0),
('Central African Republic', 'CF', 'CFA Franc BEAC', '', '+236', 0),
('Chad', 'TD', 'CFA Franc BEAC', '', '+235', 0),
('Chile', 'CL', 'Chilean Peso', '$', '+56', 0),
('China', 'CN', 'Yuan Renminbi', '¥', '+86', 0),
('Christmas Island', 'CX', 'Australian Dollar', '$', '+61', 0),
('Cocos (Keeling) Islands', 'CC', 'Australian Dollar', '$', '+61', 0),
('Colombia', 'CO', 'Colombian Peso', '$', '+57', 0),
('Comoros', 'KM', 'Comoro Franc', '', '+269', 0),
('Congo', 'CG', 'CFA Franc BEAC', '', '+242', 0),
('Congo, the Democratic Republic of the', 'CD', '', '', '+243', 0),
('Cook Islands', 'CK', 'New Zealand Dollar', '$', '+682', 0),
('Costa Rica', 'CR', 'Costa Rican Colon', '₡', '+506', 0),
('Croatia', 'HR', 'Croatian Kuna', 'kn', '+385', 0),
('Cuba', 'CU', 'Cuban Peso', '₱', '+53', 0),
('Curaçao', 'CW', 'Netherlands Antillean Guilder', 'ƒ', '+599', 0),
('Cyprus', 'CY', 'Euro', '€', '+357', 0),
('Czech Republic', 'CZ', 'Czech Koruna', 'Kč', '+420', 0),
('Denmark', 'DK', 'Danish Krone', 'kr', '+45', 0),
('Djibouti', 'DJ', 'Djibouti Franc', '', '+253', 0),
('Dominica', 'DM', 'East Caribbean Dollar', '$', '+1', 0),
('Dominican Republic', 'DO', 'Dominican Peso', '', '+1', 0),
('Ecuador', 'EC', 'US Dollar', '$', '+593', 0),
('Egypt', 'EG', 'Egyptian Pound', '£', '+20', 0),
('El Salvador', 'SV', 'US Dollar', '$', '+503', 0),
('Equatorial Guinea', 'GQ', 'CFA Franc BEAC', '', '+240', 0),
('Eritrea', 'ER', 'Nakfa', '', '+291', 0),
('Estonia', 'EE', 'Euro', '€', '+372', 0),
('Ethiopia', 'ET', 'Ethiopian Birr', 'Br', '+251', 0),
('Falkland Islands (Malvinas)', 'FK', 'Falkland Islands Pound', '£', '+500', 0),
('Faroe Islands', 'FO', 'Danish Krone', 'kr', '+298', 0),
('Fiji', 'FJ', 'Fiji Dollar', '$', '+679', 0),
('Finland', 'FI', 'Euro', '€', '+358', 0),
('France', 'FR', 'Euro', '€', '+33', 0),
('French Guiana', 'GF', 'Euro', '€', '+594', 0),
('French Polynesia', 'PF', 'CFP Franc', '', '+689', 0),
('French Southern Territories', 'TF', 'Euro', '€', '+262', 0),
('Gabon', 'GA', 'CFA Franc BEAC', '', '+241', 0),
('Gambia', 'GM', 'Dalasi', '', '+220', 0),
('Georgia', 'GE', 'Lari', '', '+995', 0),
('Germany', 'DE', 'Euro', '€', '+49', 0),
('Ghana', 'GH', 'Ghana Cedi', '', '+233', 0),
('Gibraltar', 'GI', 'Gibraltar Pound', '£', '+350', 0),
('Greece', 'GR', 'Euro', '€', '+30', 0),
('Greenland', 'GL', 'Danish Krone', 'kr', '+299', 0),
('Grenada', 'GD', 'East Caribbean Dollar', '$', '+1', 0),
('Guadeloupe', 'GP', 'Euro', '€', '+590', 0),
('Guam', 'GU', 'US Dollar', '$', '+1', 0),
('Guatemala', 'GT', 'Quetzal', 'Q', '+502', 0),
('Guernsey', 'GG', 'Pound Sterling', '£', '+44', 0),
('Guinea', 'GN', 'Guinea Franc', '', '+224', 0),
('Guinea-Bissau', 'GW', 'CFA Franc BCEAO', '', '+245', 0),
('Guyana', 'GY', 'Guyana Dollar', '$', '+592', 0),
('Haiti', 'HT', 'US Dollar', '$', '+509', 0),
('Heard Island and McDonald Islands', 'HM', 'Australian Dollar', '$', '+672', 0),
('Holy See (Vatican City State)', 'VA', 'Euro', '€', '+39', 0),
('Honduras', 'HN', 'Lempira', 'L', '+504', 0),
('Hong Kong', 'HK', 'Hong Kong Dollar', '$', '+852', 0),
('Hungary', 'HU', 'Forint', 'Ft', '+36', 0),
('Iceland', 'IS', 'Iceland Krona', 'kr', '+354', 0),
('India', 'IN', 'Indian Rupee', '₹', '+91', 0),
('Indonesia', 'ID', 'Rupiah', 'Rp', '+62', 0),
('Iran, Islamic Republic of', 'IR', 'Iranian Rial', '﷼', '+98', 0),
('Iraq', 'IQ', 'Iraqi Dinar', '', '+964', 0),
('Ireland', 'IE', 'Euro', '€', '+353', 0),
('Isle of Man', 'IM', 'Pound Sterling', '£', '+44', 0),
('Israel', 'IL', 'New Israeli Sheqel', '₪', '+972', 0),
('Italy', 'IT', 'Euro', '€', '+39', 0),
('Jamaica', 'JM', 'Jamaican Dollar', 'J$', '+1', 0),
('Japan', 'JP', 'Yen', '¥', '+81', 0),
('Jersey', 'JE', 'Pound Sterling', '£', '+44', 0),
('Jordan', 'JO', 'Jordanian Dinar', '', '+962', 0),
('Kazakhstan', 'KZ', 'Tenge', 'лв', '+7', 0),
('Kenya', 'KE', 'Kenyan Shilling', 'KSh', '+254', 1),
('Kiribati', 'KI', 'Australian Dollar', '$', '+686', 0),
('Korea, Republic of', 'KR', 'Won', '₩', '+82', 0),
('Kuwait', 'KW', 'Kuwaiti Dinar', '', '+965', 0),
('Kyrgyzstan', 'KG', 'Som', 'лв', '+996', 0),
('Latvia', 'LV', 'Euro', '€', '+371', 0),
('Lebanon', 'LB', 'Lebanese Pound', '£', '+961', 0),
('Lesotho', 'LS', 'Rand', 'R', '+266', 0),
('Liberia', 'LR', 'Liberian Dollar', '$', '+231', 0),
('Libya', 'LY', 'Libyan Dinar', '', '+218', 0),
('Liechtenstein', 'LI', 'Swiss Franc', 'CHF', '+423', 0),
('Lithuania', 'LT', 'Euro', '€', '+370', 0),
('Luxembourg', 'LU', 'Euro', '€', '+352', 0),
('Macao', 'MO', 'Pataca', '', '+853', 0),
('Macedonia, the Former Yugoslav Republic of', 'MK', 'Denar', 'ден', '+389', 0),
('Madagascar', 'MG', 'Malagasy Ariary', '', '+261', 0),
('Malawi', 'MW', 'Kwacha', '', '+265', 0),
('Malaysia', 'MY', 'Malaysian Ringgit', 'RM', '+60', 0),
('Maldives', 'MV', 'Rufiyaa', '', '+960', 0),
('Mali', 'ML', 'CFA Franc BCEAO', '', '+223', 0),
('Malta', 'MT', 'Euro', '€', '+356', 0),
('Marshall Islands', 'MH', 'US Dollar', '$', '+692', 0),
('Martinique', 'MQ', 'Euro', '€', '+596', 0),
('Mauritania', 'MR', 'Ouguiya', '', '+222', 0),
('Mauritius', 'MU', 'Mauritius Rupee', '₨', '+230', 0),
('Mayotte', 'YT', 'Euro', '€', '+262', 0),
('Mexico', 'MX', 'Mexican Peso', '$', '+52', 0),
('Micronesia, Federated States of', 'FM', 'US Dollar', '$', '+691', 0),
('Moldova, Republic of', 'MD', 'Moldovan Leu', '', '+373', 0),
('Monaco', 'MC', 'Euro', '€', '+377', 0),
('Mongolia', 'MN', 'Tugrik', '₮', '+976', 0),
('Montenegro', 'ME', 'Euro', '€', '+382', 0),
('Montserrat', 'MS', 'East Caribbean Dollar', '$', '+1', 0),
('Morocco', 'MA', 'Moroccan Dirham', '', '+212', 0),
('Mozambique', 'MZ', 'Mozambique Metical', 'MT', '+258', 0),
('Myanmar', 'MM', 'Kyat', '', '+95', 0),
('Namibia', 'NA', 'Rand', 'R', '+264', 0),
('Nauru', 'NR', 'Australian Dollar', '$', '+674', 0),
('Nepal', 'NP', 'Nepalese Rupee', '₨', '+977', 0),
('Netherlands', 'NL', 'Euro', '€', '+31', 0),
('New Caledonia', 'NC', 'CFP Franc', '', '+687', 0),
('New Zealand', 'NZ', 'New Zealand Dollar', '$', '+64', 0),
('Nicaragua', 'NI', 'Cordoba Oro', 'C$', '+505', 0),
('Niger', 'NE', 'CFA Franc BCEAO', '', '+227', 0),
('Nigeria', 'NG', 'Naira', '₦', '+234', 0),
('Niue', 'NU', 'New Zealand Dollar', '$', '+683', 0),
('Norfolk Island', 'NF', 'Australian Dollar', '$', '+672', 0),
('Northern Mariana Islands', 'MP', 'US Dollar', '$', '+1', 0),
('Norway', 'NO', 'Norwegian Krone', 'kr', '+47', 0),
('Oman', 'OM', 'Rial Omani', '﷼', '+968', 0),
('Pakistan', 'PK', 'Pakistan Rupee', '₨', '+92', 0),
('Palau', 'PW', 'US Dollar', '$', '+680', 0),
('Palestine, State of', 'PS', '', '', '+970', 0),
('Panama', 'PA', 'US Dollar', '$', '+507', 0),
('Papua New Guinea', 'PG', 'Kina', '', '+675', 0),
('Paraguay', 'PY', 'Guarani', 'Gs', '+595', 0),
('Peru', 'PE', 'Nuevo Sol', 'S/.', '+51', 0),
('Philippines', 'PH', 'Philippine Peso', 'Php', '+63', 0),
('Pitcairn', 'PN', 'New Zealand Dollar', '$', '+870', 0),
('Poland', 'PL', 'Zloty', 'zł', '+48', 0),
('Portugal', 'PT', 'Euro', '€', '+351', 0),
('Puerto Rico', 'PR', 'US Dollar', '$', '+1', 0),
('Qatar', 'QA', 'Qatari Rial', '﷼', '+974', 0),
('Romania', 'RO', 'New Romanian Leu', 'lei', '+40', 0),
('Russian Federation', 'RU', 'Russian Ruble', 'руб', '+7', 0),
('Rwanda', 'RW', 'Rwanda Franc', 'RF', '+250', 0),
('Réunion', 'RE', 'Euro', '€', '+262', 0),
('Saint Barthélemy', 'BL', 'Euro', '€', '+590', 0),
('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'Saint Helena Pound', '£', '+290', 0),
('Saint Kitts and Nevis', 'KN', 'East Caribbean Dollar', '$', '+1', 0),
('Saint Lucia', 'LC', 'East Caribbean Dollar', '$', '+1', 0),
('Saint Martin (French part)', 'MF', 'Euro', '€', '+590', 0),
('Saint Pierre and Miquelon', 'PM', 'Euro', '€', '+508', 0),
('Saint Vincent and the Grenadines', 'VC', 'East Caribbean Dollar', '$', '+1', 0),
('Samoa', 'WS', 'Tala', '', '+685', 0),
('San Marino', 'SM', 'Euro', '€', '+378', 0),
('Sao Tome and Principe', 'ST', 'Dobra', '', '+239', 0),
('Saudi Arabia', 'SA', 'Saudi Riyal', '﷼', '+966', 0),
('Senegal', 'SN', 'CFA Franc BCEAO', '', '+221', 0),
('Serbia', 'RS', 'Serbian Dinar', 'Дин.', '+381', 0),
('Seychelles', 'SC', 'Seychelles Rupee', '₨', '+248', 0),
('Sierra Leone', 'SL', 'Leone', '', '+232', 0),
('Singapore', 'SG', 'Singapore Dollar', '$', '+65', 0),
('Sint Maarten (Dutch part)', 'SX', 'Netherlands Antillean Guilder', 'ƒ', '+1', 0),
('Slovakia', 'SK', 'Euro', '€', '+421', 0),
('Slovenia', 'SI', 'Euro', '€', '+386', 0),
('Solomon Islands', 'SB', 'Solomon Islands Dollar', '$', '+677', 0),
('Somalia', 'SO', 'Somali Shilling', 'Sh.So.', '+252', 0),
('South Africa', 'ZA', 'Rand', 'R', '+27', 0),
('South Georgia and the South Sandwich Islands', 'GS', '', '', '+500', 0),
('South Sudan', 'SS', 'South Sudanese Pound', 'SSP', '+211', 0),
('Spain', 'ES', 'Euro', '€', '+34', 0),
('Sri Lanka', 'LK', 'Sri Lanka Rupee', '₨', '+94', 0),
('Sudan', 'SD', 'Sudanese Pound', '', '+249', 0),
('Suriname', 'SR', 'Surinam Dollar', '$', '+597', 0),
('Svalbard and Jan Mayen', 'SJ', 'Norwegian Krone', 'kr', '+47', 0),
('Swaziland', 'SZ', 'Lilangeni', '', '+268', 0),
('Sweden', 'SE', 'Swedish Krona', 'kr', '+46', 0),
('Switzerland', 'CH', 'Swiss Franc', 'CHF', '+41', 0),
('Syrian Arab Republic', 'SY', 'Syrian Pound', '£', '+963', 0),
('Taiwan, Province of China', 'TW', 'New Taiwan Dollar', 'NT$', '+886', 0),
('Tajikistan', 'TJ', 'Somoni', '', '+992', 0),
('Tanzania, United Republic of', 'TZ', 'Tanzanian Shilling', 'TSh', '+255', 0),
('Thailand', 'TH', 'Baht', '฿', '+66', 0),
('Timor-Leste', 'TL', 'US Dollar', '$', '+670', 0),
('Togo', 'TG', 'CFA Franc BCEAO', '', '+228', 0),
('Tokelau', 'TK', 'New Zealand Dollar', '$', '+690', 0),
('Tonga', 'TO', 'Pa’anga', '', '+676', 0),
('Trinidad and Tobago', 'TT', 'Trinidad and Tobago Dollar', 'TT$', '+1', 0),
('Tunisia', 'TN', 'Tunisian Dinar', '', '+216', 0),
('Turkey', 'TR', 'Turkish Lira', 'TL', '+90', 0),
('Turkmenistan', 'TM', 'Turkmenistan New Manat', '', '+993', 0),
('Turks and Caicos Islands', 'TC', 'US Dollar', '$', '+1', 0),
('Tuvalu', 'TV', 'Australian Dollar', '$', '+688', 0),
('Uganda', 'UG', 'Uganda Shilling', 'USh', '+256', 0),
('Ukraine', 'UA', 'Hryvnia', '₴', '+380', 0),
('United Arab Emirates', 'AE', 'UAE Dirham', '', '+971', 0),
('United Kingdom', 'GB', 'Pound Sterling', '£', '+44', 0),
('United States', 'US', 'US Dollar', '$', '+1', 0),
('United States Minor Outlying Islands', 'UM', 'US Dollar', '$', '+1', 0),
('Uruguay', 'UY', 'Peso Uruguayo', '$U', '+598', 0),
('Uzbekistan', 'UZ', 'Uzbekistan Sum', 'лв', '+998', 0),
('Vanuatu', 'VU', 'Vatu', '', '+678', 0),
('Venezuela, Bolivarian Republic of', 'VE', 'Bolivar', 'Bs', '+58', 0),
('Viet Nam', 'VN', 'Dong', '₫', '+84', 0),
('Virgin Islands, British', 'VG', 'US Dollar', '$', '+1', 0),
('Virgin Islands, U.S.', 'VI', 'US Dollar', '$', '+1', 0),
('Wallis and Futuna', 'WF', 'CFP Franc', '', '+681', 0),
('Western Sahara', 'EH', 'Moroccan Dirham', '', '+212', 0),
('Yemen', 'YE', 'Yemeni Rial', '﷼', '+967', 0),
('Zambia', 'ZM', 'Zambian Kwacha', '', '+260', 0),
('Zimbabwe', 'ZW', 'Zimbabwe Dollar', '', '+263', 0),
('Åland Islands', 'AX', 'Euro', '€', '+358', 0);